# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://swindon.hackspace.org.uk
title: Swindon Hackspace
# subtitle: A blogging framework for hackers.
author: Swindon Hackspace
simple_search: http://google.com/search
description:

# License Info
license_text: CC BY-NC-SA
license_info: "Except where otherwise noted, content on this site is licensed under a Creative Commons BY-NC-SA 3.0 License"
license_link: http://git.io/snhack-license
license_full: http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en
# license_button: http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png
# license_button: http://mirrors.creativecommons.org/presskit/icons/cc.large.png

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
# permalink: /blog/:year/:month/:day/:title/
permalink: /blog/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
category_feeds: true
category_meta_description_prefix: 'Articles for Category: '
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

# Enable kramdown for footnote support
# From: http://canadian-fury.com/2012/04/26/footnotify-and-octopress/
markdown: kramdown
# markdown: rdiscount

kramdown:
  use_coderay: true
  coderay:
    coderay_tab_width: 2
    coderay_css: style          # or class
    coderay_line_numbers: nil   # or table, inline
  toc_levels: 1..2              # header levels used for toc

paginate: 5           # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [custom/asides/recent_posts.html, custom/asides/rss_feed.html, custom/asides/github.html, custom/asides/twitter.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Group
group: &group http://groups.google.com/group/swindon-hackspace

# YouTube
youtube: snhackspace

# RSS Feed
rss_feed_title: "Group"
rss_item_count: 5
rss_feed_title_url: *group
rss_feed_url: https://groups.google.com/forum/feed/swindon-hackspace/topics/rss_v2_0.xml
rss_feed_include_link_to_feed: false
rss_feed_link_title: "Group Feed"
rss_title_length: 30

# Github repositories
github_user: snhack
github_repo_count: 5
github_show_profile_link: false
github_skip_forks: false
github_skip_sites: true

# Twitter
twitter_user: snhack
twitter_tweet_count: 2
twitter_show_replies: false
twitter_show_retweets: true
twitter_show_dates: false
twitter_show_users: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_count: none
twitter_tweet_button: true
twitter_widget_id: 356204429415956482

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-42399191-1

# Facebook Like
facebook_like: false
